# SITE SETUP
appearance:
  mode: system
  color: indigo

marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: ''
    twitter: ''
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    block: 'navbar'
    fixed_to_top: true
    show_search: false        # 单页站点一般不需要站内搜索
    show_theme_chooser: false
    logo:
      text: 'Yuchen XU'       # ← 左上角名称

# Site footer
footer:
  copyright:
    notice: '© {year} Yuchen Xu. All rights reserved.'  # ← 版权署名
    license:
      enable: false            # 你不想展示开源许可就设为 false

# Localization（日期样式可按喜好调整）
locale:
  date_format: '2006-01-02'    # ISO 风格：YYYY-MM-DD
  time_format: '15:04'         # 24 小时制

# Site features
features:
  math:
    enable: false
  privacy_pack:
    enable: false
